### PR TITLE
Hide posts from the support category on the profile page

### PR DESCRIPTION
**Pull request by ShlomoCode**
Hi,
There is currently a bug in the plugin that can be seen on the user's profile page, in his recent/best posts section, also posts from the support category. This PR came to solve this.
(Not `https://forum.com/user/user-name/posts` already fixed by filterPids function, but` https://forum.com/user/user-name`).

>Thanks to @barisusakli for the name of the hook needed to make the repair!
https://community.nodebb.org/post/88399

### CODE REVIEW

**Comment by ShlomoCode** [comment]
@julianlam Would you be able to take a look at it?

**Comment by julianlam** [comment]
Yes, I was working on a fix on Friday when I ran out of time 😐

**Comment by ShlomoCode** [comment]
Ok, I'll wait 😃

**Comment by julianlam** [comment]
a385d5f

**Comment by ShlomoCode** [comment]
@julianlam OK, so this is probably the difference between a core key and an external donor... 😃
Anyway, the fix I brought is already being used in my forum :)

**Pull request closed without merging**
